"""init

迁移 ID: 072361e8936f
父迁移: None
创建时间: 2026-04-01 14:22:31.037500

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "072361e8936f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "libamrita_global_insights",
        sa.Column("date", sa.String(length=64), nullable=False),
        sa.Column(
            "token_input", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "token_output", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_libamrita_global_insights")),
        info={"bind_key": "nonebot_plugin_amrita"},
    )
    op.create_table(
        "libamrita_user_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("last_active", sa.DateTime(), nullable=False),
        sa.Column("total_called_count", sa.BigInteger(), nullable=False),
        sa.Column("total_input_token", sa.BigInteger(), nullable=False),
        sa.Column("total_output_token", sa.BigInteger(), nullable=False),
        sa.Column("tokens_input", sa.BigInteger(), nullable=False),
        sa.Column("tokens_output", sa.BigInteger(), nullable=False),
        sa.Column("called_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_libamrita_user_metadata")),
        sa.UniqueConstraint("user_id", name="uq_amrita_user_metadata_user_id"),
        info={"bind_key": "nonebot_plugin_amrita"},
    )
    with op.batch_alter_table("libamrita_user_metadata", schema=None) as batch_op:
        batch_op.create_index(
            "idx_am_amrita_user_id_last_active",
            ["user_id", "last_active"],
            unique=False,
        )

    op.create_table(
        "libamrita_memory_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "memory_json", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("extra_prompt", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["libamrita_user_metadata.user_id"],
            name=op.f("fk_libamrita_memory_data_user_id_libamrita_user_metadata"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_libamrita_memory_data")),
        sa.UniqueConstraint("user_id", name="uq_amrita_memory_user_id"),
        info={"bind_key": "nonebot_plugin_amrita"},
    )
    op.create_table(
        "libamrita_memory_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["libamrita_user_metadata.user_id"],
            name=op.f("fk_libamrita_memory_sessions_user_id_libamrita_user_metadata"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_libamrita_memory_sessions")),
        info={"bind_key": "nonebot_plugin_amrita"},
    )
    with op.batch_alter_table("libamrita_memory_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_am_sessions_created_at_time", ["created_at"], unique=False
        )
        batch_op.create_index("idx_am_sessions_user_id", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libamrita_memory_sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_am_sessions_user_id")
        batch_op.drop_index("idx_am_sessions_created_at_time")

    op.drop_table("libamrita_memory_sessions")
    op.drop_table("libamrita_memory_data")
    with op.batch_alter_table("libamrita_user_metadata", schema=None) as batch_op:
        batch_op.drop_index("idx_am_amrita_user_id_last_active")

    op.drop_table("libamrita_user_metadata")
    op.drop_table("libamrita_global_insights")
    # ### end Alembic commands ###
