"""init

迁移 ID: 072361e8936f
uff父迁移：None
创建时间：2026-04-01 14:22:31.037500

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "072361e8936f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###

    # 检查表是否存在
    bind = op.get_context().bind
    if bind is None:
        raise RuntimeError("Database bind is not available")
    inspector = sa.inspect(bind)
    table_names = inspector.get_table_names()

    # 创建 amrita_global_insights 表（如果不存在）
    if "amrita_global_insights" not in table_names:
        op.create_table(
            "amrita_global_insights",
            sa.Column("date", sa.String(length=64), nullable=False),
            sa.Column(
                "token_input",
                sa.BigInteger(),
                server_default=sa.text("0"),
                nullable=False,
            ),
            sa.Column(
                "token_output",
                sa.BigInteger(),
                server_default=sa.text("0"),
                nullable=False,
            ),
            sa.Column("usage_count", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("date", name=op.f("pk_amrita_global_insights")),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 创建 amrita_user_metadata 表（如果不存在）
    if "amrita_user_metadata" not in table_names:
        op.create_table(
            "amrita_user_metadata",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.String(length=64), nullable=False),
            sa.Column("last_active", sa.DateTime(), nullable=False),
            sa.Column("total_called_count", sa.BigInteger(), nullable=False),
            sa.Column("total_input_token", sa.BigInteger(), nullable=False),
            sa.Column("total_output_token", sa.BigInteger(), nullable=False),
            sa.Column("tokens_input", sa.BigInteger(), nullable=False),
            sa.Column("tokens_output", sa.BigInteger(), nullable=False),
            sa.Column("called_count", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_user_metadata")),
            sa.UniqueConstraint("user_id", name="uq_amrita_user_metadata_user_id"),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 处理 amrita_user_metadata 表的索引：先检查索引是否存在再删除
    # 获取表的所有索引
    indexes = []
    if "amrita_user_metadata" in table_names:
        indexes = [idx["name"] for idx in inspector.get_indexes("amrita_user_metadata")]

    with op.batch_alter_table("amrita_user_metadata", schema=None) as batch_op:
        # 如果索引存在则删除
        if "idx_amrita_user_id_last_active" in indexes:
            batch_op.drop_index("idx_amrita_user_id_last_active")
        # 创建索引
        batch_op.create_index(
            "idx_amrita_user_id_last_active",
            ["user_id", "last_active"],
            unique=False,
        )

    # 创建 amrita_memory_data 表（如果不存在）
    if "amrita_memory_data" not in table_names:
        op.create_table(
            "amrita_memory_data",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.String(length=64), nullable=False),
            sa.Column(
                "memory_json", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
            ),
            sa.Column("extra_prompt", sa.Text(), nullable=False),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["amrita_user_metadata.user_id"],
                name=op.f("fk_amrita_memory_data_user_id_amrita_user_metadata"),
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_memory_data")),
            sa.UniqueConstraint("user_id", name="uq_amrita_memory_user_id"),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 创建 amrita_memory_sessions 表（如果不存在）
    if "amrita_memory_sessions" not in table_names:
        op.create_table(
            "amrita_memory_sessions",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.String(length=64), nullable=False),
            sa.Column("created_at", sa.Float(), nullable=False),
            sa.Column(
                "data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["amrita_user_metadata.user_id"],
                name=op.f("fk_amrita_memory_sessions_user_id_amrita_user_metadata"),
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_memory_sessions")),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 处理 amrita_memory_sessions 表的索引：先检查索引是否存在再删除
    # 获取表的所有索引
    memory_session_indexes = []
    if "amrita_memory_sessions" in table_names:
        memory_session_indexes = [
            idx["name"] for idx in inspector.get_indexes("amrita_memory_sessions")
        ]

    with op.batch_alter_table("amrita_memory_sessions", schema=None) as batch_op:
        # 如果索引存在则删除
        if "idx_am_sessions_created_at_time" in memory_session_indexes:
            batch_op.drop_index("idx_am_sessions_created_at_time")
        if "idx_am_sessions_user_id" in memory_session_indexes:
            batch_op.drop_index("idx_am_sessions_user_id")
        # 创建索引
        batch_op.create_index(
            "idx_am_sessions_created_at_time", ["created_at"], unique=False
        )
        batch_op.create_index("idx_am_sessions_user_id", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###

    # 获取数据库检查器
    bind = op.get_context().bind
    if bind is None:
        raise RuntimeError("Database bind is not available")
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    # 处理 amrita_memory_sessions 表的索引：仅在表存在时删除索引
    if "amrita_memory_sessions" in tables:
        # 获取表的所有索引
        memory_session_indexes = [
            idx["name"] for idx in inspector.get_indexes("amrita_memory_sessions")
        ]
        with op.batch_alter_table("amrita_memory_sessions", schema=None) as batch_op:
            # 如果索引存在则删除
            if "idx_am_sessions_user_id" in memory_session_indexes:
                batch_op.drop_index("idx_am_sessions_user_id")
            if "idx_am_sessions_created_at_time" in memory_session_indexes:
                batch_op.drop_index("idx_am_sessions_created_at_time")

    # 删除表（仅当存在时）
    if "amrita_memory_sessions" in tables:
        op.drop_table("amrita_memory_sessions")

    if "amrita_memory_data" in tables:
        op.drop_table("amrita_memory_data")

    # 处理 amrita_user_metadata 表的索引：仅在表存在时删除索引
    if "amrita_user_metadata" in tables:
        # 获取表的所有索引
        user_indexes = [
            idx["name"] for idx in inspector.get_indexes("amrita_user_metadata")
        ]
        with op.batch_alter_table("amrita_user_metadata", schema=None) as batch_op:
            # 如果索引存在则删除
            if "idx_amrita_user_id_last_active" in user_indexes:
                batch_op.drop_index("idx_amrita_user_id_last_active")

    # 删除表（仅当存在时）
    if "amrita_user_metadata" in tables:
        op.drop_table("amrita_user_metadata")

    if "amrita_global_insights" in tables:
        op.drop_table("amrita_global_insights")

    # ### end Alembic commands ###
